CREATE DATABASE IF NOT EXISTS radio_if CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE radio_if;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  celular VARCHAR(20) NOT NULL,
  telefone VARCHAR(20),
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(120) NOT NULL,
  numero VARCHAR(10) NOT NULL,
  bairro VARCHAR(80) NOT NULL,
  cidade VARCHAR(80) NOT NULL,
  uf CHAR(2) NOT NULL,
  administrador BOOLEAN DEFAULT 0,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS programas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  descricao TEXT,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  dia_semana ENUM('domingo','segunda','terça','quarta','quinta','sexta','sábado') NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS noticias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  conteudo TEXT NOT NULL,
  imagem_url VARCHAR(255),
  id_autor INT,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_autor) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS contatos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  assunto VARCHAR(100) NOT NULL,
  tipo_assunto VARCHAR(50) NOT NULL, 
  mensagem TEXT NOT NULL,
  data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS equipe (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  funcao VARCHAR(120),
  foto_url VARCHAR(255),
  instagram VARCHAR(255),
  linkedin VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE slides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  imagem_url VARCHAR(255) NOT NULL,
  badge VARCHAR(60) DEFAULT NULL,
  ordem INT DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
